name: Auto approve data PRs

on:
  pull_request:
    types:
      - labeled
    
permissions:
  contents: read
  pull-requests: write
  
jobs:
  autoapproval:
    name: Auto approve data PRs
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'auto-approved') }}
    runs-on: ubuntu-latest
    steps:
      - uses: dkhmelenko/autoapproval@v1.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.PR_APPROVER_TOKEN }}