name: Auto approve data PRs

on:
  pull_request:
    types: [opened, reopened, labeled, edited]
  pull_request_review:
    types: [dismissed]
    
permissions:
  contents: read
  pull-requests: write
  
jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Auto approve data PRs
    steps:
      - uses: dkhmelenko/autoapproval@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.PR_APPROVER_TOKEN }}