name: Run CBOM on Requests

on:
  workflow_dispatch:

jobs:
  requests:
    uses: ./.github/workflows/cbom-reusable-workflow.yml
    with:
      repositoryNameWithOwner: psf/requests
    secrets: inherit
