name: Run CBOM on top 2000 Python repos

on:
  workflow_dispatch:
    inputs:
      subsetRange:
        description: The range of repositories to analyze from pqc.json
        type: string
        required: false
        default: ":250"
      listSelector:
        description: The list of repositories to analyze from pqc.json
        type: string
        required: false
        default: "python_2000_all"

jobs:
  build-matrix:
    name: Build analysis matrix
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.build-matrix.outputs.repositories }}
    steps:
      - uses: actions/checkout@v4
      - id: build-matrix
        run: |
          set -ex
          REPOS=$(cat pqc.json | jq -c '.${{ inputs.listSelector }}[${{ inputs.subsetRange }}]')
          echo "repositories=${REPOS}" >> "$GITHUB_OUTPUT"
  batch:
    uses: ./.github/workflows/cbom-batch-reusable-workflow.yml
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.build-matrix.outputs.repositories) }}
    with:
        repositoryNameWithOwner: ${{ matrix.repository }}
        postSummary: false
    secrets: inherit
  commit-data:
    name: Commit data back to repo
    runs-on: ubuntu-latest
    needs: batch
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: cbom-results
          path: ${{ github.workspace }}/cbom-results
      - run: |
          # Commit data to new branch and create PR
          set -ex
          BRANCH_NAME="${{ inputs.listSelector }}-python-${{ github.run_id }}-${{ github.run_attempt }}"
          git switch -c "${BRANCH_NAME}"
          rsync -a ./cbom-results/ ./data/
          git config --global user.name 'CBOM Data Action'
          git config --global user.email 'advanced-security@users.noreply.github.com'
          git add ./data
          git commit -m "${{ inputs.listSelector }}-${{ github.run_id }}-${{ github.run_attempt }}"
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create \
            --title "${{ inputs.listSelector }}[${{ inputs.subsetRange }}] run #${{ github.run_id }} attempt #${{ github.run_attempt }}" \
            --fill --label data-pr
          gh pr merge --rebase --auto 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
