name: Run CBOM Reusable Workflow

on:
  workflow_call:
    inputs:
      repositoryNameWithOwner:
        type: string
        required: true
      analyzeDependencies:
        type: boolean
        required: false
        default: false
      requestGitHubAnalysis:
        type: boolean
        required: false
        default: false

jobs:
  build-matrix:
    name: Build analysis matrix
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.build-matrix-action.outputs.repositories }}
    steps:
      - uses: advanced-security/cbom-action/build-matrix@main
        id: build-matrix-action
        with:
          repositoryNameWithOwner: ${{ inputs.repositoryNameWithOwner }}
          minimumLanguageBytes: 2000
          analyzeDependencies: ${{ inputs.analyzeDependencies }}
  run-cbom-action:
    name: ${{ fromJson(matrix.repository).nameWithOwner }} - ${{ fromJson(matrix.repository).language }}
    runs-on: ubuntu-latest
    needs: build-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.build-matrix.outputs.repositories) }}
    steps:
      - uses: advanced-security/cbom-action/analyze@main
        with:
          repositoryNameWithOwner: ${{ fromJson(matrix.repository).nameWithOwner }}
          language: ${{ fromJson(matrix.repository).language }}
          createCodeQLDatabaseIfRequired: true
          requestGitHubAnalysis: ${{ inputs.requestGitHubAnalysis }}
  commit-data:
    name: Commit data back to repo
    runs-on: ubuntu-latest
    needs: run-cbom-action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: cbom-results
          path: ${{ github.workspace }}/cbom-results
      - run: |
          # Commit data to new branch and create PR
          IFS=/ read -r REPO_OWNER REPO_NAME <<< ${{ inputs.repositoryNameWithOwner }}
          BRANCH_NAME="${REPO_OWNER}-${REPO_NAME}-${{ github.run_id }}-${{ github.run_attempt }}"
          git switch -c "${BRANCH_NAME}"
          rsync -ai ./cbom-results/ ./data/
          git config --global user.name 'CBOM Data Action'
          git config --global user.email 'advanced-security@users.noreply.github.com'
          git add ./data
          git commit -m "${{ inputs.repositoryNameWithOwner }}"
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create --head --title "${BRANCH_NAME}" --body "" --reviewer @ctcampbell
        shell: bash -ex {0}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add-workflow-summary:
    name: CBOM results
    runs-on: ubuntu-latest
    needs: run-cbom-action
    steps:
      - uses: advanced-security/cbom-action/workflow-summary@main
 
