name: Attempt to run PQC on analysis request

on:
  repository_dispatch:
    types:
      - analysis-requested

jobs:
  run-pqc-action:
    name: ${{ github.event.client_payload.repositoryNameWithOwner }} - ${{ github.event.client_payload.language }}
    runs-on: ubuntu-latest
    steps:
      - uses: pre-quantum-research/pqc-action/analyze@main
        with:
          repositoryNameWithOwner: ${{ github.event.client_payload.repositoryNameWithOwner }}
          language: ${{ github.event.client_payload.language }}
          createCodeQLDatabaseIfRequired: true
          actionsTokensAppId: ${{ secrets.ACTIONS_TOKENS_APP_ID }}
          actionsTokensPrivateKey: ${{ secrets.ACTIONS_TOKENS_PRIVATE_KEY }}
  commit-data:
    name: Commit data back to repo
    runs-on: ubuntu-latest
    needs: run-pqc-action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: pqc-results
          path: ${{ github.workspace }}/pqc-results
      - run: |
          rsync -ai ./pqc-results/ ./data/
          git config --global user.name 'PQC Data Action'
          git config --global user.email 'pre-quantum-research@users.noreply.github.com'
          git add ./data
          git commit -m "${{ inputs.repositoryNameWithOwner }}"
          git push
  add-workflow-summary:
    name: PQC results
    runs-on: ubuntu-latest
    needs: run-pqc-action
    steps:
      - uses: pre-quantum-research/pqc-action/workflow-summary@main
