name: Run PQC Reusable Workflow

on:
  workflow_call:
    inputs:
      repositoryNameWithOwner:
        type: string
        required: true

jobs:
  build-matrix:
    name: Build analysis matrix
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.build-matrix-action.outputs.repositories }}
    steps:
      - uses: pre-quantum-research/pqc-action/build-matrix@main
        id: build-matrix-action
        with:
          repositoryNameWithOwner: ${{ inputs.repositoryNameWithOwner }}
          minimumLanguageBytes: 2000
          analyzeDependencies: true
  run-pqc-action:
    name: ${{ fromJson(matrix.repository)[0] }} - ${{ fromJson(matrix.repository)[1] }}
    runs-on: ubuntu-latest
    needs: build-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.build-matrix.outputs.repositories) }}
    steps:
      - uses: pre-quantum-research/pqc-action/analyze@main
        with:
          repositoryNameWithOwner: ${{ fromJson(matrix.repository)[0] }}
          language: ${{ fromJson(matrix.repository)[1] }}
          createCodeQLDatabaseIfRequired: false
          requestGitHubAnalysis: true
          actionsTokensAppId: ${{ secrets.ACTIONS_TOKENS_APP_ID }}
          actionsTokensPrivateKey: ${{ secrets.ACTIONS_TOKENS_PRIVATE_KEY }}
  add-workflow-summary:
    name: PQC results
    runs-on: ubuntu-latest
    needs: run-pqc-action
    steps:
      - uses: pre-quantum-research/pqc-action/workflow-summary@main
