name: Attempt to run PQC on analysis request

on:
  repository_dispatch:
    types:
      - analysis-requested

jobs:
  analysis-request:
    uses: ./.github/workflows/pqc-reusable-workflow.yml
    with:
      repositoryNameWithOwner: ${{ github.context.client_payload.repositoryNameWithOwner }}
    secrets: inherit
