name: Run PQC on Spring Boot

on:
  workflow_dispatch:

jobs:
  spring-boot:
    uses: ${{ github.repository }}/.github/workflows/pqc-reusable-workflow.yml
    with:
      repositoryNameWithOwner: spring-projects/spring-boot
