name: Run PQC Reusable Workflow

on:
  workflow_call:
    inputs:
      repositoryNameWithOwner:
        type: string
        required: true
      analyzeDependencies:
        type: string
        required: false
        default: false

jobs:
  build-matrix:
    name: Build analysis matrix
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.build-matrix-action.outputs.repositories }}
    steps:
      - uses: pre-quantum-research/pqc-action/build-matrix@main
        id: build-matrix-action
        with:
          repositoryNameWithOwner: ${{ inputs.repositoryNameWithOwner }}
          minimumLanguageBytes: 2000
          analyzeDependencies: ${{ inputs.analyzeDependencies }}
  run-pqc-action:
    name: ${{ fromJson(matrix.repository).nameWithOwner }} - ${{ fromJson(matrix.repository).language }}
    runs-on: ubuntu-latest
    needs: build-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.build-matrix.outputs.repositories) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pre-quantum-research/pqc-action/analyze@main
        with:
          repositoryNameWithOwner: ${{ fromJson(matrix.repository).nameWithOwner }}
          language: ${{ fromJson(matrix.repository).language }}
          createCodeQLDatabaseIfRequired: true
          requestGitHubAnalysis: false
          actionsTokensAppId: ${{ secrets.ACTIONS_TOKENS_APP_ID }}
          actionsTokensPrivateKey: ${{ secrets.ACTIONS_TOKENS_PRIVATE_KEY }}
  commit-data:
    name: Commit data back to repo
    runs-on: ubuntu-latest
    needs: run-pqc-action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: pqc-results
          path: ${{ github.workspace }}/pqc-results
      - run: |
          cp -rl ${{ github.workspace }}/pqc-results/* /data/
          git config --global user.name 'PQC Data Action'
          git config --global user.email 'pre-quantum-research@users.noreply.github.com'
          git add ./data
          git commit -m "${{ fromJson(matrix.repository).nameWithOwner }}/${{ fromJson(matrix.repository).language }}"
          git push
  add-workflow-summary:
    name: PQC results
    runs-on: ubuntu-latest
    needs: run-pqc-action
    steps:
      - uses: pre-quantum-research/pqc-action/workflow-summary@main
 
